src/staging/components/cross-trade/components/core/updateFee/index.tsx

- Checkbox style for cancelRequest

fix : CrossTrade - checkbox style for cancelRequest

---

src/components/modal/TxToast.tsx

- fix toast message for ETH on Cross Trade case

fix : Toast - ETH for CrossTrade

---

src/assets/icons/tooltipArrow.svg
src/components/history/AccountHistory.tsx
src/components/modal/TxToast.tsx
src/components/tooltip/CustomTooltip.tsx
src/staging/components/common/Tooltip.tsx
src/staging/components/cross-trade/components/CTCustomTooltip.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmCrossTradeFooter.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmDetail.tsx
src/staging/components/cross-trade/components/core/main/CTMain.tsx
src/staging/components/cross-trade/components/core/main/TokenDetail.tsx

fix : Cross Trade - implement design feedbacks

---

src/app/BridgeSwap/ApproveToken.tsx
src/components/tooltip/CustomTooltip.tsx
src/staging/hooks/useBridgeHistory.ts

fix : ts-error

---

src/components/history/AccountHistory.tsx
src/components/tooltip/CustomTooltip.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmCrossTradeFooter.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmHistoryFooter.tsx
src/staging/components/cross-trade/components/core/comfirm/index.tsx
src/staging/components/cross-trade/components/core/main/CTMain.tsx
src/staging/components/cross-trade/components/core/main/CTMainProvider.tsx
src/staging/components/cross-trade/components/core/option/CTOptionInput.tsx
src/staging/components/cross-trade/components/core/option/index.tsx
src/staging/components/new-history/components/core/complete/index.tsx
src/staging/hooks/useBridgeHistory.ts
src/staging/types/transaction.ts

- Implement additional feedbacks before it goes to internal testing

[BK-34] - implement additional feedbacks

---

src/staging/components/cross-trade/components/core/comfirm/index.tsx
src/staging/components/cross-trade/components/core/main/CTMainProvider.tsx
src/staging/components/cross-trade/components/core/updateFee/index.tsx

- update the edit button to updateFee modal on CtMain

[BK-34] - link edit button to updateFee modal on CtMain

---

src/components/modal/TxToast.tsx
src/graphql/queries/crossTrade.ts
src/hooks/tx/useTx.ts
src/staging/components/cross-trade/components/core/comfirm/CTConfirmCrossTradeFooter.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmHistoryFooter.tsx
src/staging/components/cross-trade/components/core/main/CTMain.tsx
src/staging/components/cross-trade/components/core/option/CTOptionInput.tsx
src/staging/components/cross-trade/components/core/option/CTOptionStandardDetail.tsx
src/staging/components/cross-trade/components/core/updateFee/CTUpdateInput.tsx
src/staging/components/new-history/components/core/index.tsx
src/staging/hooks/useBridgeHistory.ts
src/staging/hooks/useCrossTrade.ts
src/staging/utils/getRequestStatus.ts

[BK-34] - implement additional feedbacks#2

---

src/components/modal/TxToast.tsx
src/staging/components/cross-trade/components/core/main/CTMain.tsx
src/staging/components/cross-trade/components/core/option/CTOptionInput.tsx
src/staging/components/cross-trade/components/core/option/index.tsx
src/staging/components/cross-trade/components/core/updateFee/CTRefundDetail.tsx
src/staging/components/cross-trade/components/core/updateFee/CTUpdateInput.tsx
src/staging/components/cross-trade/components/core/updateFee/index.tsx

- Improve ui/ux with addtional feedbacks

[BK-34] - 

---

src/staging/components/cross-trade/components/core/updateFee/CTRefundDetail.tsx
src/staging/components/new-history/utils/getTimeDisplay.ts

- fix refund amount on updateFee
- countdown for Providing on the history tab

fix : ui issues on CrossTrade

---

.github/ISSUE_TEMPLATE/1-frontend+backend.yml
.github/ISSUE_TEMPLATE/2-contract.yml
.github/ISSUE_TEMPLATE/3-suggestions.yml

- added github issue template for cross trade public test
- [x ] Provided a screenshot (only if change is visible in UI)
- [ x] Provided steps for playback (only if possible).
- [ O] Provided a change scope in summary
- [x ] Local build has passed

added github issue template

---

.github/ISSUE_TEMPLATE/1-frontend+backend.yml
.github/ISSUE_TEMPLATE/2-contract.yml
.github/ISSUE_TEMPLATE/3-suggestions.yml

- Fixed typos and improved description for github issue format

fix typo and include better description for public test

---

src/staging/components/cross-trade/components/core/main/CTMain.tsx

- fix network symbol ui bug on Cross Trade Pool page

[BK-76] : hotfix for network symbol UI

---

.github/ISSUE_TEMPLATE/4-others.yml

- Reduce reporting of wrong feature for public test

add new template to accept bugs other than cross trade

---

.github/workflows/shared-deploy.yaml

fix: remove env in deploy command

---

src/app/layout.tsx
src/components/trackAnalytics.tsx
src/types/global.d.ts

- Added Google analytics tracker on tokamak bridge

feat: add google tracker

---

src/components/footer/index.tsx
src/components/header/Index.tsx
src/components/header/Network.tsx
src/components/history/AccountHistory.tsx
src/components/modal/Confirmation.tsx
src/components/ui/GradientSpinner.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmCrossTradeFooter.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmHistoryFooter.tsx
src/staging/components/cross-trade/components/core/comfirm/index.tsx
src/staging/components/cross-trade/components/core/main/CTMain.tsx
src/staging/components/cross-trade/components/core/main/CTMainProvider.tsx
src/staging/components/cross-trade/components/core/main/TokenDetail.tsx
src/staging/components/new-history/components/core/index.tsx
src/staging/hooks/useBridgeHistory.ts
src/staging/hooks/useCrossTrade.ts
src/staging/utils/formatProfit.ts

- fix issues
- #126
- #134
- #159
- #172
- #173
- #177
- #183
- #191

[BK-76] - fix issues from public test

---

src/app/Modals.tsx
src/components/header/Network.tsx
src/components/tooltip/CustomTooltip.tsx
src/components/ui/WarningText.tsx
src/constant/index.ts
src/hooks/time/useTimeOver.ts
src/recoil/modal/atom.ts
src/staging/components/cross-trade/components/core/comfirm/CTConfirmCrossTradeFooter.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmDetail.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmHistoryFooter.tsx
src/staging/components/cross-trade/components/core/comfirm/CTRefresh.tsx
src/staging/components/cross-trade/components/core/comfirm/index.tsx
src/staging/components/cross-trade/components/core/main/CTMainProvider.tsx
src/staging/components/cross-trade/components/core/main/TokenDetail.tsx
src/staging/components/cross-trade/components/core/updateFee/CTRefundDetail.tsx
src/staging/components/cross-trade/hooks/useCTConfirmModal.ts
src/staging/hooks/useBridgeHistory.ts
src/staging/hooks/useCrossTrade.ts

- Implemented all issues from public test for Cross Trade part
- Improve Modal UI with tooltips for the amount

[BK-76] - Final Check : Implemented All Requested Changes

---

src/staging/components/cross-trade/components/core/comfirm/CTBetaWarning.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmCrossTradeFooter.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmDetail.tsx
src/staging/components/cross-trade/components/core/option/CTOptionDisabledDetail.tsx
src/types/token/supportedToken.ts

- fix issues which not correctly fixed 
- fix Cross Trade beta UI

[BK-115] - Cross Trade Beta UI Fixes & Issue Resolution

---

src/staging/components/cross-trade/components/core/comfirm/CTBetaWarning.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmCrossTradeFooter.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmDetail.tsx
src/staging/components/cross-trade/components/core/comfirm/CTNetworkTransition.tsx
src/staging/components/cross-trade/components/core/comfirm/index.tsx
src/staging/components/cross-trade/components/core/main/index.tsx

- Fix UI issues
- Implement new UI for Cross Trade Beta

[BK-115] - Fix UI Issues and Implement New UI for Cross Trade Beta

---

src/app/BridgeSwap/Index.tsx
src/components/header/Index.tsx
src/constant/contracts/crossTrade.ts
src/staging/components/cross-trade/components/core/main/CTMain.tsx
src/staging/components/cross-trade/components/core/main/CTMainProvider.tsx
src/staging/components/cross-trade/components/core/main/index.tsx

- Cross Trade Subgraphs on Ethereum and Titan
- Bind Cross Trade contract addresses on Ethereum and Titan 
- UI text changes

[BK-94] - Setup Cross Trade Service on Production env

---

src/staging/components/cross-trade/components/core/main/CTMain.tsx
src/staging/hooks/useCrossTrade.ts

- fix the issue with Cross Trade Subgraph on Titan
- fix code conflicts with mobile part

[BK-95] - fix requestList on mainnet env

---

src/staging/components/cross-trade/hooks/useRecommendFee.ts
src/staging/hooks/useBridgeHistory.ts
src/staging/hooks/useCrossTrade.ts
src/staging/utils/getRequestStatus.ts
src/utils/token/getSupportedTokenInfo.ts

- fix Subgraph issues on Titan 
- fix minor bugs with useCrossTrade hook

[BK-95] - fix subgraph issues

---

src/app/pools/add/ActionButton.tsx
src/recoil/crosstrade/networkFee.ts
src/staging/components/cross-trade/components/core/comfirm/CTConfirmCrossTradeFooter.tsx
src/staging/components/cross-trade/components/core/comfirm/index.tsx
src/staging/components/cross-trade/components/core/option/CTOptionStandardDetail.tsx
src/staging/components/cross-trade/components/core/updateFee/index.tsx
src/staging/components/new-confirm/hooks/useGetGas.ts
src/staging/constants/fee.ts
src/staging/hooks/useCrossTradeContracts.ts
src/staging/hooks/useCrossTradeGasFee.ts
src/utils/txn/calculateGasMargin.ts

- Implement logic to calculate network fees for Cross Trade functionalities.
- Update the flow to retrieve gas fees for standard withdrawals.
- Apply a 1.25x buffer to all gas fee calculations.

[BK-95] - network fee UI

---

src/app/BridgeSwap/Details.tsx
src/app/BridgeSwap/components/ActionButton.tsx
src/staging/components/cross-trade/components/core/main/CTMain.tsx
src/staging/components/cross-trade/components/core/main/CTMainProvider.tsx
src/staging/components/cross-trade/components/core/main/TokenDetail.tsx
src/staging/components/cross-trade/components/core/option/CTOptionCrossDetail.tsx
src/staging/components/cross-trade/components/core/option/CTOptionInput.tsx
src/staging/components/cross-trade/components/core/option/CTOptionStandardDetail.tsx
src/staging/components/cross-trade/components/core/option/index.tsx
src/staging/components/cross-trade/hooks/useCTGas.ts
src/staging/components/cross-trade/hooks/useRecommendFee.ts
src/staging/components/new-confirm/hooks/useGetGas.ts
src/staging/constants/fee.ts
src/staging/hooks/useCrossTrade.ts
src/staging/types/crossTrade.ts
src/staging/utils/formatProfit.ts

- Implement net profit calculation for Cross Trade liquidity.
- Implement new UI for the withdraw option when the recommended fee exceeds the withdrawal amount.
- Adjust the calculation method for the recommended fee.

[BK-95] - New UI for Cross Trade 

---

src/staging/components/new-history/components/core/pending/PendingFooter.tsx
src/staging/components/new-history/components/core/pending/StatusComponent.tsx
src/staging/components/new-history/utils/getTimeDisplay.ts
src/staging/components/new-history/utils/historyStatus.ts
src/staging/constants/transactionTime.ts
src/staging/hooks/useBridgeHistory.ts
src/test/deposit/_mock/mockdata.ts
src/test/withdraw/_mock/mockdata.ts
src/utils/history/getTransaction.ts

- Fix styles for Deposit and Withdraw across different stages in the history tab.
- Additional style adjustments are needed for the modal.

[Bk-123] - Fix the history tab with Deposit & Withdraw

---

src/staging/components/cross-trade/components/core/comfirm/CTConfirmHistoryFooter.tsx
src/staging/components/cross-trade/components/core/main/CTMain.tsx
src/staging/components/cross-trade/components/core/main/TokenDetail.tsx
src/staging/components/cross-trade/components/core/updateFee/CTUpdateInput.tsx
src/staging/components/cross-trade/hooks/useRecommendFee.ts
src/staging/components/new-confirm/components/core/other/index.tsx
src/staging/components/new-history/components/core/pending/StatusComponent.tsx
src/staging/components/new-history/components/core/pending/index.tsx
src/staging/hooks/useBridgeHistory.ts

- Fix Net Profit percentage.
- Immediately update Cross Trade request in the history tab after it's provided.
- Apply token decimals to recommendedFeeAmount.
- Add a warning about non-real-time updates to all confirm modals.
-

[BK-126] - reflect mainnet test fixes

---

src/staging/components/cross-trade/components/core/main/TokenDetail.tsx
src/staging/components/cross-trade/components/core/option/CTOptionStandardDetail.tsx
src/staging/components/new-confirm/hooks/useGetGas.ts
src/staging/hooks/useCrossTrade.ts

- Fix sort by net profit percentage 
- Add withdraw initiate gas fee to the Withdraw Option UI

[BK-126] - reflect testnet test issues

---

src/staging/components/cross-trade/components/core/main/TokenDetail.tsx
src/staging/hooks/useCrossTrade.ts
src/staging/types/crossTrade.ts
src/types/token/supportedToken.ts

- profit usd value calculated by profitUSD 
- remove TOS in the hand-ui

[BK-126] - fix mainnet test issues

---

src/staging/components/cross-trade/components/core/comfirm/CTBetaWarning.tsx
src/staging/components/cross-trade/components/core/comfirm/CTConfirmCrossTradeFooter.tsx
src/staging/components/new-confirm/utils/getConfirmType.ts
src/staging/constants/transactionTime.ts

- Change warning and confirm text for Cross Trade Beta Phrase
- Change rollup time on mainnet (6 hour -> 6 hours 20 min)

[BK-126] - Cross Trade Beta UI

---

src/staging/components/new-confirm/utils/getConfirmType.ts
src/staging/constants/transactionTime.ts

- Apply 15sec time-buffer for deposit time on UI purpose
- Remove using undefined as string in the Confirm Withdraw modal

[BK-126] - UI fixes

---

src/staging/components/new-confirm/components/core/other/index.tsx

- Remove real time warning on the deposit initiate confirm

[BK-126] - UI fix

---

src/staging/components/new-confirm/components/core/other/index.tsx

- Remove real time warning on the deposit initiate confirm

[BK-77] - Update Release v1.2

---

src/staging/components/cross-trade/components/core/main/CTMainProvider.tsx

- Remove countdown on the Cross Trade page
- Change a label for the provided ticket

[BK-127] - hotfix_1

---

src/staging/components/cross-trade/components/core/comfirm/CTConfirmCrossTradeFooter.tsx
src/staging/components/cross-trade/components/core/main/CTMainProvider.tsx
src/staging/components/cross-trade/hooks/useRecommendFee.ts

- Show network fee when it's not in the situation calculating in the Confirm Provide modal
- Remove adjust fee machanism
- Fix completed label design on the Cross Trade Requests page

[BK-127] - hotfix_2

---

src/staging/hooks/useCrossTrade.ts

- Change polling interval 5sec -> 13sec

[BK-132] - Extend polling interval

---

src/graphql/thegraph/apollosForCT.ts
src/staging/hooks/useCrossTrade.ts

- apply cache policy for useCrossTradeData

[BK-132] - cache policy 

---

src/staging/components/cross-trade/hooks/useRecommendFee.ts
src/staging/constants/fee.ts

- Change additional fee based on updated model

[BK-127] - Change additiona fee %

---

src/app/BridgeSwap/components/ActionButton.tsx
src/recoil/modal/atom.ts
src/staging/components/cross-trade/components/core/option/index.tsx
src/staging/components/cross-trade/hooks/useCTOptionModal.ts

- Fix Next button condition bug
- Allow go to Withdraw Option modal with insufficient balance

[BK-127] - Withdraw UI change

---

src/app/BridgeSwap/components/ActionButton.tsx
src/recoil/modal/atom.ts
src/staging/components/cross-trade/components/core/option/index.tsx
src/staging/components/cross-trade/hooks/useCTOptionModal.ts

- Fix button condition on WIthdraw Option when it's on the insufficient balance case

[BK-127] - Fix button condition bug

---

src/staging/components/cross-trade/components/core/option/CTOptionCrossDetail.tsx
src/staging/components/cross-trade/components/core/option/CTOptionInput.tsx
src/staging/components/cross-trade/components/core/option/index.tsx
src/staging/components/cross-trade/types/index.ts
src/staging/constants/fee.ts

- Change additional fee % for TON (4.565753% -> 6.476712%)
- Update Cross Trade Request confirm UI

[BK-127] - Apply changes related to Cross Trade functionality

---

src/app/BridgeSwap/components/ActionButton.tsx

[BK-131] Hot fix: the deposit was not working

---

src/components/header/Index.tsx

[BK-135] - Fix the Get Help link

---

src/staging/components/cross-trade/hooks/useRecommendFee.ts

- Fix one missing dependency in the process for recommendedFee

[BK-138] - Fix recommendedFee

---

src/app/BridgeSwap/components/ActionButton.tsx

- Fix a connect wallet func on the main screen

[hotfix] - connect wallet

---

src/app/BridgeSwap/components/ActionButton.tsx

clean up console log

---

src/app/BridgeSwap/components/ActionButton.tsx
src/staging/components/cross-trade/hooks/useRecommendFee.ts

- Fix the connect wallet func on the main screen

[hotfix] - connect wallet 

---

src/graphql/thegraph/apollo.ts

- Fix subgraph issue on Uniswap Pools page

[BK-149] - hotfix Subgraph issue on Uniswap Pools

---

src/app/BridgeSwap/Index.tsx
src/constant/url/index.ts
src/staging/components/legacy-titan/InitialBanner.tsx
src/staging/constants/banner.ts

Add banner 1.0

---

src/staging/components/legacy-titan/InitialBanner.tsx

fix: typo on banner title

---

src/app/BridgeSwap/Index.tsx
src/app/BridgeSwap/components/ActionButton.tsx
src/constant/url/index.ts
src/staging/components/legacy-titan/Banner10.tsx
src/staging/components/legacy-titan/Banner11.tsx
src/staging/constants/banner.ts
src/staging/constants/legacyTitan.ts
src/staging/types/legacyTitan.ts

Victor/feature/banner 1.1

---

src/staging/constants/legacyTitan.ts

rollback to bridge 0.1

---

src/staging/components/legacy-titan/Banner10.tsx
src/staging/components/legacy-titan/Banner11.tsx
src/staging/constants/legacyTitan.ts

update banner 1.0 and 1.1

---

src/app/BridgeSwap/Index.tsx
src/staging/components/legacy-titan/WarningModal10.tsx

add bridge warning modal 1.0

---

src/staging/constants/legacyTitan.ts

update titan network maintanence date
